### ISSUE TITLE
bug: hyper63 DATA query command using Couchdb Adapter

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper63#100]
@Benanna2019 reported a bug when using the query selector request and a couchdb adapter, the returned data was not correctly filtering the documents based on the selector.

ie:

POST /data/{name}/_query

```
{
  "selector": {
     "type" : "foo"
   }
}
```

would return documents of type "foo" and "bar"

**Comment by Benanna2019** [comment]
So this bug was a little premature. Last week I was running the wrong request. It was returning me the data it was supposed to for running GET. 

I tested it today running POST and there is no issue

**Comment by twilson63** [comment]
Cool
