### ISSUE TITLE
refactor: adapter-couchdb to deno

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper63#215]
Making progress, have tests mock for createDatabase and removeDatabase

Tests
- [x] createDatabase
- [x] removeDatabase
- [x] createDocument
- [x] can't create design doc
- [x] retrieve document
- [x] find/query document
- [x] create index
- [x] list documents
- [x] bulk documents

**Comment by twilson63** [comment]
Making progress, have tests mock for createDatabase and removeDatabase

Tests
- [ ] createDatabase
- [ ] removeDatabase
- [ ] createDocument
- [ ] can't create design doc
- [ ] retrieve document
- [ ] find/query document
- [ ] create index
- [ ] list documents
