### ISSUE TITLE
chore: Change Repo name to hyper

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper63#239]
Change repo name to `hyper` and config file to `hyper.config.js`

**Comment by TillaTheHun0** [comment]
Typically, I would say let's make this backwards compatible and support `hyper.config.js` and `hyper63.config.js`.Given that we know about all users of hyper right now, perhaps we just make the breaking change and update all users?

It's also not difficult to just support both.

**Comment by twilson63** [comment]
I am good either way

**Comment by TillaTheHun0** [comment]
PR on #240
